# This is a basic workflow to help you get started with Actions

name: Weppack do it

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # push 到 master 分支時會觸發
  push:
    branches: [ actions-ci ]
  # 排程每天 UTC 16:30 (台灣時間 0:30) 時觸發
  # 語法可上 crontab.guru 查詢
  # schedule:
  # - cron: 30 16 * * *
  # pull_request:
  #   branches: [ master ]
    
jobs:
  build_and_package:
    runs-on: ubuntu-latest
    name: webpack build
    
    strategy:
      matrix:
        node_version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
  
      - run: npm install
      - run: npm build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist/
            !dist/**/*.md
          if-no-files-found: error
#       - name: Archive code coverage results
#         uses: actions/upload-artifact@v2
#         with:
#           name: code-coverage-report
#           path: output/test/code-coverage.html
